apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: tipc-ingress
  namespace: tipc
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules:
    - http:
        paths:
          - path: /tipc-backend(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: tipc-backend-service
                port: 
                  number: 80
          - path: /tipc
            pathType: Prefix
            backend:
              service:
                name: tipc-frontend-service
                port: 
                  number: 80
              
          
                  
      