apiVersion: apps/v1
kind: Deployment
metadata:
  name: tipc-backend
  namespace: tipc
spec:
  replicas: 2
  selector:
    matchLabels:
      app: tipc-backend
  template:
    metadata:
      labels:
        app: tipc-backend
    spec:
      containers:
      - name: tipc-backend
        image: youngjay9/tipc:202307241517
        ports:
        - containerPort: 8083
      imagePullSecrets:
      - name: regcred
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tipc-frontend
  namespace: tipc
spec:
  replicas: 2
  selector:
    matchLabels:
      app: tipc-frontend
  template:
    metadata:
      labels:
        app: tipc-frontend
    spec:
      containers:
      - name: tipc-frontend
        image: youngjay9/tipc-frontend:202307252355
        ports:
        - containerPort: 8080
      imagePullSecrets:
      - name: regcred