apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-claim
spec:
  capacity:
    storage: 1000Gi
  accessModes:
    - ReadWriteMany
  claimRef:
    name: force-nfs
    namespace: default
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 192.168.56.10
    path: /nfsshare