apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: force-nfs
  namespace: default
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi