#╔════════════════════════════════════════════════╗#
#║                 本地端測試環境                      ║#
#╚════════════════════════════════════════════════╝#

environment: DEV


#╔═════════════════════════════════════════════════╗#
#║             Server port & context-path          ║#
#╚═════════════════════════════════════════════════╝#
server:
  port: 8080
  servlet:
    context-path: /temp-api

#╔═════════════════════════════════════════════════╗#
#║               Application settings              ║#
#╚═════════════════════════════════════════════════╝#
spring:
    application:
      name: Temp